<?php

namespace App\Traits;

use App\Models\Opinion;

trait HasSlug
{
    protected static function boot():void
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function (Opinion $opinion) {
            $opinion->slug = \Str::random();
        });
    }
}
